startHeight: -50
borderSize: 220
version: '${project.version}' # DEFINITELY DON'T CHANGE / KESİNLİKLE DEĞİŞTİRME
block: LAVA
gracePeriod: 12 # minutes/dakika (THIS IS CAN'T BE UNDER ZERO/BU SIFIRIN ALTINDA OLAMAZ)
increaseAmount: 2
inviteExpire: 60 # seconds/saniye
language: en # avaible/kullanılabilir: en/tr
lang:
  tr:
    eliterising.main.error: "HATA"
    eliterising.main.invalidBlock: "Ayarlar dosyasında geçersiz blok bulundu: '$' ve 'LAVA' olarak düzeltildi"
    eliterising.main.notReal: "Komutu gönderen bir oyuncu olmalı!"
    eliterising.main.notEnoughPerm: "Bu komutu kullanmak için yeterli izniniz yok!"
    eliterising.cmd.invite.gameStart: "Davet komutu lav yükselmeden önce kullanılabilir!"
    eliterising.cmd.invite.welcomeTeam: "Yeni takımına hoş geldin"
    eliterising.cmd.invite.accepted1: "Takım davetin kabul edildi."
    eliterising.cmd.invite.invalid: "Geçersiz Davet"
    eliterising.cmd.invite.expired: "Davetin süresi doldu"
    eliterising.cmd.invite.rejectedTeam: "Davet reddedildi"
    eliterising.cmd.invite.rejected1: "$, davetini reddetti."
    eliterising.cmd.invite.reAccept.suc1: "Daveti kabul ettin"
    eliterising.cmd.invite.reAccept.suc2: "$, davetini kabul etti."
    eliterising.cmd.invite.JSON.generic: "$ takımına katılırken, şuanki takımından ayrılacaksın. Kabul ediyor musun?"
    eliterising.cmd.invite.JSON.yes: "[EVET]"
    eliterising.cmd.invite.JSON.no: "[HAYIR]"
    eliterising.cmd.invite.JSON.yesHover: "Kabul Ediyorum"
    eliterising.cmd.invite.JSON.noHover: "Kabul Etmiyorum"
    eliterising.cmd.stats.mostKill: "En çok öldüren"
    eliterising.cmd.stats.mostTD: "En çok hasar alan"
    eliterising.cmd.stats.mostDD: "En çok hasar veren"
    eliterising.cmd.stats.mostAssist: "En çok asist"
    eliterising.cmd.stats.kills: "Öldürme"
    eliterising.cmd.stats.td: "Alınan Hasar"
    eliterising.cmd.stats.dd: "Verilen Hasar"
    eliterising.cmd.stats.assist: "Asist"
    eliterising.cmd.stats.gameFinish: "İstatistikler komutu sadece oyun bittiğinde kullanılabilir!"
    eliterising.cmd.mode.nonOp: "Lütfen bir işlem girin"
    eliterising.cmd.mode.invalidOp: "Lütfen geçerli bir işlem girin"
    eliterising.cmd.mode.nonModeName: "Lütfen bir mod ismi girin"
    eliterising.cmd.mode.nonHandle: "Ana modları düzenleyemezsiniz"
    eliterising.cmd.mode.nonItems: "Lütfen verilecek eşyaları giriniz"
    eliterising.cmd.mode.createSuc: "Özel oyun modu başarıyla oluşturuldu!"
    eliterising.cmd.mode.editSuc: "Oyun modu başarıyla düzenlendi!"
    eliterising.cmd.mode.removeSuc: "Başlangıç modu başarıyla silindi!"
    eliterising.cmd.mode.listAllTeams: "Tüm Özel Başlangıç Modları:"
    eliterising.cmd.mode.info.onlyEnch: "Sadece Büyü"
    eliterising.cmd.mode.info.onlyAmount: "Sadece Miktar, Büyüsüz"
    eliterising.cmd.mode.info.both: "Miktarlı ve Büyülü"
    eliterising.cmd.mode.info.generic: "NBT tagları miktardan önce gelir. Miktar belirten sayı daima eğik çizgiyle (/) başlar. JSON ve NBT'lerde eğik çizgi kullanamazsınız."
    eliterising.cmd.start.gameStart: "Oyun zaten başladı"
    eliterising.cmd.start.periodUnderZero: "Hazırlık süresi sıfırın altında bir değer olamaz."
    eliterising.cmd.start.invalidStartMode: "Lütfen geçerli bir oyun modu girin"
    eliterising.cmd.start.invalidTeamMode: "Lütfen geçerli bir takım modu girin"
    eliterising.cmd.start.incompatibleNumber: "Oyuncu sayısı bu takım moduna uymuyor"
    eliterising.cmd.start.remainTime: "Kalan Süre"
    eliterising.cmd.start.hours: "Saat"
    eliterising.cmd.start.mins: "Dakika"
    eliterising.cmd.start.secs: "Saniye"
    eliterising.cmd.start.startTitle: "OYUN BAŞLADI!"
    eliterising.cmd.start.modeTitle: "Mod"
    eliterising.cmd.start.riseSecs: "$ Saniye Sonra Lav Yükselecek!"
    eliterising.cmd.start.rising: "Lav Yükseliyor!"
    eliterising.cmd.start.maxLevel: "Lav Maksimum Seviyede"
    eliterising.cmd.team.notStarted: "Takım komutunun çalışabilmesi için oyunun başlaması gerek"
    eliterising.cmd.team.nonNormal: "Takım komutları sadece normal modda çalışır"
    eliterising.cmd.team.nonOp: "Lütfen bir işlem girin"
    eliterising.cmd.team.invalidOp: "Lütfen geçerli bir işlem girin"
    eliterising.cmd.team.createRising: "Takım oluşturma komutu sadece lav yükselmeden önce kullanılabilir!"
    eliterising.cmd.team.createHaveTeam: "Zaten bir takımın var"
    eliterising.cmd.team.createSuc: "Takım başarıyla oluşturuldu"
    eliterising.cmd.team.leaveRising: "Takımdan ayrılma komutu sadece lav yükselmeden önce kullanılabilir!"
    eliterising.cmd.team.leaveNoTeam: "Ayrılmak için bir takımın olmalı"
    eliterising.cmd.team.leaveSuc: "Takımdan ayrıldın"
    eliterising.cmd.team.inviteRising: "Takıma davet komutu sadece lav yükselmeden önce kullanılabilir!"
    eliterising.cmd.team.inviteNoTeam: "Davet edecek bir takımın yok"
    eliterising.cmd.team.invite404Player: "Oyuncu bulunamadı"
    eliterising.cmd.team.inviteSuc: 'Takım daveti $ adlı oynucuya gönderildi!'
    eliterising.cmd.team.invite.JSON.generic: "sana bir davet gönderdi!"
    eliterising.cmd.team.invite.JSON.accept: "[KABUL ET]"
    eliterising.cmd.team.invite.JSON.acceptHover: "Daveti kabul et"
    eliterising.cmd.team.invite.JSON.reject: "[REDDET]"
    eliterising.cmd.team.invite.JSON.rejectHover: "Daveti reddet"
    eliterising.cmd.team.invite.expired: "$ adlı oyuncuya gönderdiğin davetin süresi doldu"
    eliterising.cmd.team.msg.noTeam: "Mesaj atacak bir takımın yok"
    eliterising.cmd.team.msg.team: "Takım"
    eliterising.cmd.list.allTeams: "Tüm takımlar"
    eliterising.cmd.list.noTeams: "Takım Yok"
    eliterising.cmd.list.urTeam: "Senin Takım"
    eliterising.cmd.list.no: "Yok"
    eliterising.cmd.invites.mines: "Davetlerim"
    eliterising.cmd.invites.receiver: "Alıcı"
    eliterising.cmd.version.suc: "EliteRising Sürümü"
    eliterising.cmd.version.suc1: "Minecraft Sürümü"
    eliterising.cmd.config.gameStarted: "Ayarlar komutu sadece oyun başlamadan önce kullanılabilir!"
    eliterising.cmd.config.nonOp: "Lütfen bir işlem giriniz"
    eliterising.cmd.config.nonValue: "Lütfen bir değer giriniz"
    eliterising.cmd.config.invalidValue: "Lütfen geçerli bir değer giriniz"
    eliterising.cmd.config.invalidOp: "Lütfen geçerli bir işlem giriniz"
    eliterising.cmd.config.nonSetting: "Lütfen bir ayar giriniz"
    eliterising.cmd.config.invalidSetting: "Lütfen geçerli bir ayar giriniz"
    eliterising.cmd.config.invalidLang: "Lütfen geçerli bir dil giriniz"
    eliterising.cmd.config.cExpire: "Geçerli Davet Dolma Süresi (sn)"
    eliterising.cmd.config.sucExpire: "Davet dolma süresi başarıyla ayarlandı"
    eliterising.cmd.config.cHeight: "Geçerli Başlangıç Yüksekliği"
    eliterising.cmd.config.sucHeight: "Başlangıç yüksekliği başarıyla ayarlandı"
    eliterising.cmd.config.cAmount: "Geçerli Yükselme Katsayısı"
    eliterising.cmd.config.sucAmount: "Yükselme katsayısı başarıyla ayarlandı"
    eliterising.cmd.config.cSize: "Geçerli Duvar Boyutu"
    eliterising.cmd.config.sucSize: "Duvar boyutu başarıyla ayarlandı"
    eliterising.cmd.config.cLang: "Geçerli Dil"
    eliterising.cmd.config.sucLang: "Dil başarıyla ayarlandı"
    eliterising.cmd.config.cPeriod: "Geçerli Hazırlık Süresi (dk)"
    eliterising.cmd.config.sucPeriod: "Hazırlık süresi başarıyla ayarlandı"
    eliterising.cmd.info.generic: "$EliteRising'e hoş geldiniz. Komutlar: %/başlat $, %/takım $, %/mod$. %/başlat $komutuyla oyunu başlatabilirsin. %/takım $ile sadece normal takım modunda takımları yönetebilirsin. Ayrıca SADECE oyun modlarını özelleştirebilirsin. Yapabileceğin şeyler: %Yeni mod oluşturmak$, %Özel oyun modları düzenlemek. (5 ana oyun modunu ÖZELLEŞTİREMEZSİN)$, %Modları listelemek yada silmek (Yine ana modları silemezsin)"
    eliterising.events.chat.general: "Genel"
    eliterising.events.chat.team: "Takım"
    eliterising.events.damage.hitTeammate: "Takım arkadaşına vuramazsın"
    eliterising.events.death.died: "öldü."
    eliterising.events.death.killedMsg: "$, % tarafından öldürüldü"
    eliterising.events.death.eliminated: "[ELENDİ]"
    eliterising.events.death.uDied: "ÖLDÜN!"
    eliterising.events.death.wonGame: "oyunu kazandı"
    eliterising.events.death.fly: "Artık uçabilirsin!"
    eliterising.events.death.winner: "[KAZANAN]"
    eliterising.events.death.won: "KAZANDINIZ!"
    eliterising.events.death.lost: "KAYBETTİNİZ!"
    eliterising.events.death.pRemain: "Son $ oyuncu kaldı."
    eliterising.events.join.generic: "oyuna katıldı"
    eliterising.events.join.info1: "%EliteRising'e hoş geldiniz"
    eliterising.events.join.info2: "%Oyunu başlatmak için: &/başlat <Oyun Modu> <Takım Modu>"
    eliterising.events.join.info3: "%Takım komutları için: &/takım <create|leave|invite|invites|message|list>"
    eliterising.events.join.info4: "&Özelleştirilebilir oyun modları için: &/mod <create|edit|list|info|delete> <eşyalar... (eğer sadece ilk argüman oluştur veya düzenleyse)>"
    eliterising.events.join.info5: "%Genele mesaj atmak için, mesajın başına &! %koymanız yeterlidir. Ancak takımın yoksa mesajın başında başında ne olursa olsun genele mesaj atarsın"
    eliterising.events.join.info6: "&Sadece Emir %tarafından geliştirildi."
    eliterising.events.quit.generic: "ayrıldı!"
  en:
    eliterising.main.error: "ERROR"
    eliterising.main.invalidBlock: "Found invalid block at config file: '$' fixed to 'LAVA'"
    eliterising.main.notReal: "Sender must be a real player!"
    eliterising.main.notEnoughPerm: "You have no permission to run this command!"
    eliterising.cmd.invite.gameStart: "Invite command is just usable before lava rises!"
    eliterising.cmd.invite.welcomeTeam: "Welcome to your new team"
    eliterising.cmd.invite.accepted1: "Your team invite has accepted"
    eliterising.cmd.invite.invalid: "Invalid Invite"
    eliterising.cmd.invite.expired: "Invite was expired"
    eliterising.cmd.invite.rejectedTeam: "Rejected invite"
    eliterising.cmd.invite.rejected1: "Your team invite has rejected by $"
    eliterising.cmd.invite.reAccept.suc1: "You has accepted the invite"
    eliterising.cmd.invite.reAccept.suc2: "Your team invite has accepted by $"
    eliterising.cmd.invite.JSON.generic: "While joining to team called $, you will leave your current team. Do you accept?"
    eliterising.cmd.invite.JSON.yes: "[YES]"
    eliterising.cmd.invite.JSON.no: "[NO]"
    eliterising.cmd.invite.JSON.yesHover: "I accept"
    eliterising.cmd.invite.JSON.noHover: "I ain't accept"
    eliterising.cmd.stats.mostKill: "Most Kills"
    eliterising.cmd.stats.mostTD: "Most Taken Damage"
    eliterising.cmd.stats.mostDD: "Most Dealt Damage"
    eliterising.cmd.stats.mostAssist: "Most Assist"
    eliterising.cmd.stats.kills: "Kills"
    eliterising.cmd.stats.td: "Taken Damage"
    eliterising.cmd.stats.dd: "Dealt Damage"
    eliterising.cmd.stats.assist: "Assists"
    eliterising.cmd.stats.gameFinish: "Stats command is just usable after game"
    eliterising.cmd.mode.nonOp: "Please select an operation"
    eliterising.cmd.mode.invalidOp: "Please select a valid operation"
    eliterising.cmd.mode.nonModeName: "Please enter a mode name"
    eliterising.cmd.mode.nonHandle: "You cannot handle main modes"
    eliterising.cmd.mode.nonItems: "Please enter items"
    eliterising.cmd.mode.createSuc: "Custom game mode has successfully created"
    eliterising.cmd.mode.editSuc: "Custom game mode has successfully edited"
    eliterising.cmd.mode.removeSuc: "Custom game mode has successfully removed"
    eliterising.cmd.mode.listAllTeams: "All Custom Start Modes:"
    eliterising.cmd.mode.info.onlyEnch: "Only enchantment"
    eliterising.cmd.mode.info.onlyAmount: "Only amount, No enchantment"
    eliterising.cmd.mode.info.both: "Both Amount and Enchantment"
    eliterising.cmd.mode.info.generic: "While writing, NBT tag (only enchantments for now) comes before amount. Amount number always has a prefix slash. You can't use slash JSONs or NBTs."
    eliterising.cmd.start.gameStart: "Game already started"
    eliterising.cmd.start.invalidStartMode: "Please enter a valid game mode"
    eliterising.cmd.start.invalidTeamMode: "Please enter a valid team mode"
    eliterising.cmd.start.periodUnderZero: "Grace period cannot be under zero value."
    eliterising.cmd.start.incompatibleNumber: "Number of players is not compatible to this mode"
    eliterising.cmd.start.remainTime: "Remaining Time"
    eliterising.cmd.start.hours: "Hours"
    eliterising.cmd.start.mins: "Minutes"
    eliterising.cmd.start.secs: "Seconds"
    eliterising.cmd.start.startTitle: "START!"
    eliterising.cmd.start.modeTitle: "Mode"
    eliterising.cmd.start.riseSecs: "Lava will rise after $ seconds!"
    eliterising.cmd.start.rising: "Lava Rising!"
    eliterising.cmd.start.maxLevel: "Lava Maximum Level"
    eliterising.cmd.team.notStarted: "The game must be started for the team command to work"
    eliterising.cmd.team.nonNormal: "Commands related by team just work on normal team mode"
    eliterising.cmd.team.nonOp: "Please select an operation"
    eliterising.cmd.team.invalidOp: "Please select a valid operation"
    eliterising.cmd.team.createRising: "The team create command is just usable before lava rises"
    eliterising.cmd.team.createHaveTeam: "You have already a team"
    eliterising.cmd.team.createSuc: "Team successfully created"
    eliterising.cmd.team.leaveRising: "The team leave command is just usable before lava rises"
    eliterising.cmd.team.leaveNoTeam: "You must have a team to leave"
    eliterising.cmd.team.leaveSuc: "Successfully left"
    eliterising.cmd.team.invite.expired: "Your team invite sent to $ was expired"
    eliterising.cmd.team.inviteRising: "The team invite command is just usable before lava rises"
    eliterising.cmd.team.inviteNoTeam: "You have no team"
    eliterising.cmd.team.invite404Player: "Player was not found"
    eliterising.cmd.team.inviteSuc: "Team invite has successfully sent to $!"
    eliterising.cmd.team.invite.JSON.generic: "sent invite to you!"
    eliterising.cmd.team.invite.JSON.accept: "[ACCEPT]"
    eliterising.cmd.team.invite.JSON.acceptHover: "Accept the invite"
    eliterising.cmd.team.invite.JSON.reject: "[REJECT]"
    eliterising.cmd.team.invite.JSON.rejectHover: "Reject the invite"
    eliterising.cmd.team.msg.noTeam: "You have no team to message"
    eliterising.cmd.team.msg.team: "Team"
    eliterising.cmd.list.allTeams: "All Teams"
    eliterising.cmd.list.noTeams: "No Team"
    eliterising.cmd.list.urTeam: "Your Team"
    eliterising.cmd.list.no: "No"
    eliterising.cmd.invites.mines: "My Invites"
    eliterising.cmd.invites.receiver: "Receiver"
    eliterising.cmd.version.suc: "EliteRising Version"
    eliterising.cmd.version.suc1: "Minecraft Version"
    eliterising.cmd.config.gameStarted: "Config command is just usable before game starts!"
    eliterising.cmd.config.nonOp: "Please enter an operation"
    eliterising.cmd.config.nonValue: "Please enter a value"
    eliterising.cmd.config.invalidValue: "Please enter a valid value"
    eliterising.cmd.config.invalidOp: "Please enter a valid operation"
    eliterising.cmd.config.nonSetting: "Please enter a config"
    eliterising.cmd.config.invalidSetting: "Please enter a valid operation"
    eliterising.cmd.config.invalidLang: "Please enter a valid language"
    eliterising.cmd.config.cExpire: "Current Invite Expire Time (sn)"
    eliterising.cmd.config.sucExpire: "Invite expire time has successfully set"
    eliterising.cmd.config.cHeight: "Current Start Height"
    eliterising.cmd.config.sucHeight: "Start Height has successfully set"
    eliterising.cmd.config.cAmount: "Current Increase Amount"
    eliterising.cmd.config.sucAmount: "Increase Amount has successfully set"
    eliterising.cmd.config.cSize: "Current Border Size"
    eliterising.cmd.config.sucSize: "Border Size has successfully set"
    eliterising.cmd.config.cLang: "Current Language"
    eliterising.cmd.config.sucLang: "Language has successfully set"
    eliterising.cmd.config.cPeriod: "Current Grace Period (min)"
    eliterising.cmd.config.sucPeriod: "Grace Period has successfully set"
    eliterising.cmd.info.generic: "$Welcome to EliteRising. Commands are: %/start|başlat|starten $, %/elteam|takım $, %/mode|mod$. You can start the game using the command called %/start$. You can create or organize (at only normal team mode) the teams using %/elteam$. Also, you can edit ONLY game modes. What can you do: %Create a new game mode$, %Edit all CUSTOM game modes. (You CANNOT operate main 5 modes)$, %Delete or list custom game modes (Again you can't remove main modes)"
    eliterising.events.chat.general: "General"
    eliterising.events.chat.team: "Team"
    eliterising.events.damage.hitTeammate: "You cannot hit teammate"
    eliterising.events.death.died: "died."
    eliterising.events.death.killedMsg: "$ was killed by %"
    eliterising.events.death.eliminated: "[ELIMINATED]"
    eliterising.events.death.uDied: "YOU DIED!"
    eliterising.events.death.wonGame: "won the game"
    eliterising.events.death.fly: "You can fly anymore!"
    eliterising.events.death.winner: "[WINNER]"
    eliterising.events.death.won: "WON!"
    eliterising.events.death.lost: "LOST!"
    eliterising.events.death.pRemain: "Last $ player remaining."
    eliterising.events.join.generic: "joined"
    eliterising.events.join.info1: "%Welcome to &EliteRising"
    eliterising.events.join.info2: "%In order to start the game: &/start <Game Mode> <Team Mode>"
    eliterising.events.join.info3: "%For Team commands: &/elteam <create|leave|invite|invites|message|list>"
    eliterising.events.join.info4: "&For customizable game modes: &/mode <create|edit|list|info|delete> <items... (if only first argument is create or edit)>"
    eliterising.events.join.info5: "%You want to message general, you can use &! %to message's start. But you don't have to use any prefix for team"
    eliterising.events.join.info6: "%Developed by &Sadece Emir."
    eliterising.events.quit.generic: "left!"
custom_modes:
  # EN / these are example game and team modes if you want, you can delete or edit these game team modes.
  # TR / bunlar örnek oyun ve takım modlarıdır isterseniz bunları silebilir veya düzenleyebilirsiniz.
  gameModes:
    example:
      DIAMOND_SWORD:
        amount: "1"
        enchantments:
          sharpness: "5"
      SHIELD:
        amount: "1"
  teamModes:
    hepta: "7"