name: EliteRising
version: '${project.version}'
main: tr.elite.eliterising.EliteRising
api-version: 1.19
authors: [ SadeceEmir ]
permissions:
  start:
    description: Needed permission to start the EliteRising
    default: op
  language:
    description: Needed permission to change language
    default: op
commands:
  start:
    description: Start the EliteRising
    aliases:
      - başlat
      - starten
    usage: /<command> [normal|elytra|op|archery|build] [normal|solo|duo|triple|squad|penta|half]
  elteam:
    description: Command related with team.
    aliases:
      - takım
    usage: /<command> [create|leave|invite|message|list]
  mode:
    description: You can edit, create, list etc. start modes.
    aliases:
      - mod
    usage: /<command> [create|delete|edit|list|info]
  info:
    description: More informations about EliteRising
    aliases:
      - bilgi
    usage: /<command>
  elversion:
    description: Get version of current EliteRising
    aliases:
      - sürüm
    usage: /<command>
  config:
    description: Changes or gets config.yml of EliteRising
    aliases:
      - konfig
      - ayarlar
    usage: /<command> [start_height|increase_amount|border_size|language|grace_period|invite_expire] [get|set] [value]
  eldavet:
    description: The player can't direct use this command. This is in-code command. Don't use this.
    usage: /<command>
  stats:
    description: Stats for kills, assists, most taken damage, most dealt damage etc.
    usage: /<command>
    aliases:
      - istatistikler
      - statistiken